### ISSUE TITLE
improvement suggestion (cpu model name)

### ISSUE THREAD

**Issue by simon-mueller** [scar45/conky_solar_burn#2]
Hi, i tried out your conkyrc and it looks very nice. What could help others would be to replace the hardcoded cpu model name and replace it with this line:

`${execi 300 cat /proc/cpuinfo |grep 'model name'|sort -u|awk -F: '{ print $2; }'|awk -F\ \  '{print $1}'}`

Best regards
Simon

**Comment by scar45** [comment]
Thanks much! It works great, I just had to change the `awk -F\` to `awk -F:` and it reads the CPU name from `/proc/cpuinfo` -- I suppose since it was a value that never changed, it had slipped my mind to improve it, but this will make it great for others.

I have added it with  https://github.com/scar45/conky_solar_burn/commit/63f411062e71802276c17054a7b2e1fb09d62871 -- thanks again @simon-mueller!
