### ISSUE TITLE
images not update

### ISSUE THREAD

**Issue by ManuRS** [scar45/conky_solar_burn#4]
I'm using some of the code and i think the images doesnt update. 
<br />I know it comes from another conky but i dont have devian art account so... did you see the icons change? for example the current weather must change in the night.

**Comment by scar45** [comment]
Hey @manurs -- I have been checking it over the past few days, and the images/current weather are working properly. Is it still an issue for you? If so, I'd imagine it's something on your side, because the weather changes/updates have always worked for me.

Please let me know, as I am inclined to close this issue. Thanks!

**Comment by ManuRS** [comment]
In my case the images doesnt change when the data is update (only when conky start)
So I turn this:
${image ~/.cache/weather-3.png -p 167,298 -s 55x55}
into this:
${image ~/.cache/weather-3.png -p 167,298 -s 55x55 -n}

-n is the non cache flag

**Comment by scar45** [comment]
Thanks! I am going to close this issue, but will reference it in case others find that their images are not updating.
